version: 2

run:
  timeout: 5m

linters-settings:
  gocyclo:
    min-complexity: 15

  govet:
    enable-all: true

  misspell:
    locale: US

  lll:
    line-length: 120

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G304  # File path provided as taint input - acceptable for this CLI tool
      - G306  # WriteFile permissions for config files and README

  revive:
    rules:
      - name: exported

  staticcheck:
    checks: ["all"]

linters:
  enable:
    - gocyclo
    - govet
    - misspell
    - lll
    - gosec
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - revive
    - gocritic

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec

    # Exclude specific gosec rules for crypto operations
    - path: internal/cert/
      linters:
        - gosec
      text: "G401|G501"

    # Exclude line length for long test names and template strings
    - path: _test\.go
      linters:
        - lll
      source: "func Test"

    # Exclude line length for template constants
    - path: internal/templates/
      linters:
        - lll

  max-issues-per-linter: 0
  max-same-issues: 0
