version: "2"

linters:
  default: none

  enable:
    - gocyclo
    - misspell
    - lll
    - gosec
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - unconvert
    - gocritic
    - godox
    - bodyclose
    - contextcheck
    - durationcheck
    - nilerr
    - nolintlint
    - predeclared

  settings:
    gocyclo:
      min-complexity: 15

    govet:
      enable:
        - shadow
      enable-all: true

    misspell:
      locale: US

    lll:
      line-length: 120

    gosec:
      severity: medium
      confidence: medium
      excludes:
        - G304  # File path provided as taint input - acceptable for this CLI tool
        - G306  # WriteFile permissions for config files and README

    revive:
      rules:
        - name: exported

    staticcheck:
      checks: ["all"]

  exclusions:
    rules:
      # Exclude some linters from running on tests files
      - path: '_test\.go'
        linters:
          - gocyclo
          - errcheck
          - gosec
          - lll

      # Exclude specific gosec rules for crypto operations
      - path: 'internal/cert/'
        linters:
          - gosec
        text: "G401|G501"

      # Exclude line length for template constants
      - path: 'internal/templates/'
        linters:
          - lll

      # Exclude unused cmd variables (used by cobra but not directly referenced)
      - path: 'cmd/'
        linters:
          - unused
        text: "createCACmd|createCertCmd|generateConfigCmd"

      # Exclude deprecated PEM encryption warnings (needed for Java compatibility)
      - path: 'internal/cert/cert.go'
        linters:
          - staticcheck
        text: "SA1019.*EncryptPEMBlock|SA1019.*DecryptPEMBlock"

      # Exclude package comment warnings
      - linters:
          - staticcheck
        text: "ST1000"

      # Exclude comment format warnings (ST1022, ST1021)
      - linters:
          - staticcheck
        text: "ST1022|ST1021"

      # Exclude DNs naming style warnings (DNs is correct for Distinguished Names, not DNS)
      - linters:
          - staticcheck
        text: "ST1003"

      # Exclude quick fix suggestions (QF)
      - linters:
          - staticcheck
        text: "QF1003|QF1001|S1030"

      # Exclude gocyclo for complex command functions
      - path: 'cmd/create_cert.go'
        linters:
          - gocyclo

      # Exclude gocyclo for cert generation (inherently complex)
      - path: 'internal/cert/cert.go'
        linters:
          - gocyclo
