version: "2"

linters:
  default: none

  enable:
    - gocyclo
    - govet
    - misspell
    - lll
    - gosec
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - unconvert
    - revive
    - gocritic
    - godox
    - goconst
    - bodyclose
    - contextcheck
    - durationcheck
    - nilerr
    - nolintlint
    - predeclared

  settings:
    gocyclo:
      min-complexity: 15

    govet:
      enable:
        - shadow
      enable-all: true

    misspell:
      locale: US

    lll:
      line-length: 120

    gosec:
      severity: medium
      confidence: medium
      excludes:
        - G304  # File path provided as taint input - acceptable for this CLI tool
        - G306  # WriteFile permissions for config files and README

    revive:
      rules:
        - name: exported

    staticcheck:
      checks: ["all"]

  exclusions:
    rules:
      # Exclude some linters from running on tests files
      - path: '_test\.go'
        linters:
          - gocyclo
          - errcheck
          - gosec

      # Exclude specific gosec rules for crypto operations
      - path: 'internal/cert/'
        linters:
          - gosec
        text: "G401|G501"

      # Exclude line length for long test names
      - path: '_test\.go'
        linters:
          - lll
        text: "func Test"

      # Exclude line length for template constants
      - path: 'internal/templates/'
        linters:
          - lll
